### ISSUE TITLE
 grabber's size

### ISSUE THREAD

**Issue by donaldlee2008** [andreaschiavinato/python_grabber#4]
I grab image from camera in size of (480, 640) as default.  the camera is (1080,1920).
how can I set the grabber's size ?

**Comment by andreaschiavinato** [comment]
From the application you can set the resolution using the **Set format...** command from the **Camera** menu.
It's not possible at the moment to set the format by a function on the **PyGrabber** or **dshow_graph** classes. I will add it when I have time.

**Comment by donaldlee2008** [comment]
thanks

**Comment by andreaschiavinato** [comment]
I implemented this functionality, see the example `setting_format.py`

**Comment by donaldlee2008** [comment]
great
