### ISSUE TITLE
publish on pypi

### ISSUE THREAD

**Issue by sander76** [andreaschiavinato/python_grabber#8]
I'd like to use your pygrabber module to create a wxpython based qr code scanner.
https://github.com/sander76/qrabber
It would be great if you can put pygrabber on pypi.

Thanks !

**Comment by andreaschiavinato** [comment]
Thanks for using my project! I'll try to add in the future but right now I don't have much time to spend on this project...

**Comment by sander76** [comment]
That's allright.
Your repo is very interesting to me for the fact that it allows easy access to the windows webcam. Do you mind if I rip that part out, and publish it on pypi ? Fully crediting you and giving you access rights etc ?

**Comment by andreaschiavinato** [comment]
Please do!

**Comment by FlantasticDan** [comment]
I just discovered this project and it's already saved me a ton of time interfacing with the DirectShow API, thanks @andreaschiavinato for creating it!

I too would love to see this up on PyPi 😎

**Comment by sander76** [comment]
That's still my todo. But I'm not sure when I'll get to it...

**Comment by andreaschiavinato** [comment]
I finally published this on PyPi :

https://pypi.org/project/pygrabber/0.1/
